In [449]:
import numpy as np

In [450]:
# from ngaussel import ngaussel
def ngaussel(A,b):
    n = len(b)
    x = np.zeros((n,1))
    augm = np.column_stack((A,b))
    m = range(0,n-1)
    for k in range(n):
        for i in range(k+1,n):
            m = A[i][k]/A[k][k]
            for j in range(n):
                A[i][j] = A[i][j] - m*A[k][j]
            b[i] = b[i] - m*b[k]
            
    print(A)
    print(b)

    x[n-1] = b[n-1]/A[n-1][n-1]
    for i in range(n-2,-1,-1):
        S = b[i]
        for j in range(n-1,i,-1):
            S = S - A[i][j]*x[j]
        x[i] = S/A[i][i]
    print(x)

In [451]:
A = np.array([[1,1, -1],[2, -1, 1],[-1, 2, 2]])
b = np.array([[-2],[5],[1]])
ngaussel(A,b)

[[ 1  1 -1]
 [ 0 -3  3]
 [ 0  0  4]]
[[-2]
 [ 9]
 [ 8]]
[[ 1.]
 [-1.]
 [ 2.]]


In [452]:
n = 3
B = np.random.randint(1,10,size=(n,n))
c = np.random.randint(1,10, size=(n,1))
print(B)
print(c)

[[4 3 9]
 [1 5 8]
 [8 4 6]]
[[7]
 [6]
 [1]]
